
- repo: tpope/vim-surround
- repo: itchyny/vim-cursorword
- repo: wsdjeg/dein-ui.vim
- repo: rafi/awesome-vim-colorschemes
- repo: flazz/vim-colorschemes

- repo: andymass/vim-matchup
  hook_add: 
    let g:matchup_matchparen_deferred = 1

- repo: itchyny/lightline.vim
#   hook_add:
#     function! CocCurrentFunction()
#       return get(b:, 'coc_current_function', '')
#     endfunction
#
#     let g:lightline = {
#       \ 'colorscheme': 'wombat',
#       \ 'active': {
#       \   'left': [ [ 'mode', 'paste' ],
#       \             [ 'cocstatus', 'currentfunction', 'readonly', 'filename', 'modified' ] ]
#       \ },
#       \ 'component_function': {
#       \   'cocstatus': 'coc#status',
#       \   'currentfunction': 'CocCurrentFunction'
#       \ },
#       \ }
# - repo: liuchengxu/eleline.vim
#   hook_add:
#     let g:airline_powerline_fonts = 1
# - repo: vim-airline/vim-airline
#   hook_add: |
#     let g:airline_powerline_fonts=1
#     let g:airline_extensions = ['branch', 'coc']
#     let g:airline_section_error = '%{airline#util#wrap(airline#extensions#coc#get_error(),0)}'
#     let g:airline_section_warning = '%{airline#util#wrap(airline#extensions#coc#get_warning(),0)}'
# - repo: vim-airline/vim-airline-themes

- repo: christoomey/vim-tmux-navigator
  if: "! (has('win32') || has('win64'))"

- repo: 907th/vim-auto-save
  hook_add: |
    let g:auto_save = 1
    let g:auto_save_events = ["BufLeave", "FocusLost"]

- repo: junegunn/fzf
  build: './install --all'
  merged: 0
- repo: junegunn/fzf.vim
  hook_add: |
    let g:fzf_nvim_statusline = 0
    let g:fzf_preview_window = ''


# ==========================================
# Completion
# ----------

- repo: neoclide/coc.nvim
  merge: 0
  rev: release
  hook_add: source $VIM_PATH/config/plugins/coc.vim

# ==========================================
# Commands
# --------
- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source $VIM_PATH/config/plugins/defx.vim
- { repo: kristijanhusak/defx-git, on_source: defx.nvim }

- { repo: kristijanhusak/defx-icons, on_source: defx.nvim }

- repo: kana/vim-operator-user  # only autoload functions, lazy by nature
- repo: preservim/nerdcommenter
  hook_add: |
    let g:NERDCustomDelimiters = {  'hocon': { 'left': '//' } }


- repo: kana/vim-operator-replace
  depends: vim-operator-user
  on_map: { vnx: <Plug> }


# ==========================================
# GIT
# --------
- { repo: tpope/vim-fugitive}
- repo: sodapopcan/vim-twiggy
  depends: vim-fugitive
  hook_add: |
    let g:twiggy_num_columns = 50
    let g:twiggy_split_method = 'topleft'
    let g:twiggy_local_branch_sort = 'mru'
    let g:twiggy_remote_branch_sort = 'date'
- { repo: junegunn/gv.vim, depends: vim-fugitive }

- repo: tveskag/nvim-blame-line
  hook_add: |
    autocmd BufEnter * EnableBlameLine
    let g:blameLineVirtualTextPrefix = '   '
- repo: airblade/vim-gitgutter
  on_path: .*
  hook_add: |
    let g:gitgutter_map_keys = 0
    let g:gitgutter_sign_added = '▎'
    let g:gitgutter_sign_modified = '▎'
    let g:gitgutter_sign_removed = '▏'
    let g:gitgutter_sign_removed_first_line = '▔'
    let g:gitgutter_sign_modified_removed = '▋'
    let g:gitgutter_preview_win_floating = 1
    let g:gitgutter_sign_allow_clobber = 0
    let g:gitgutter_sign_priority = 0
    let g:gitgutter_override_sign_column_highlight = 0

# ==========================================
# Interface
# ---------
- { repo: haya14busa/incsearch.vim, on_map: { nv: <Plug> }}
- { repo: haya14busa/vim-asterisk, on_map: { nv: <Plug> }}
- { repo: terryma/vim-expand-region, on_map: { x: <Plug> }}
- repo: pangloss/vim-javascript
- repo: maxmellon/vim-jsx-pretty
  hook_add: | 
    let g:vim_jsx_pretty_colorful_config = 1

